### ISSUE TITLE
[Admin] - Instagram scraper is no longer working

### ISSUE THREAD

**Issue by levogirar** [wuwanahq/wuwana2#104]
<img width="497" alt="Screen Shot 2021-01-07 at 23 15 26" src="https://user-images.githubusercontent.com/54992530/103973757-3c836b80-513e-11eb-903c-dd1b9591387b.png">

**Comment by Nils85** [comment]
Have you try to change your country with the VPN?

**Comment by levogirar** [comment]
@Nils85 yes, and on Safari and Chrome. My hypothesis is that Instagram changed the data structure.

**Comment by levogirar** [comment]
Resolved by changing VPN location
