### ISSUE TITLE
Admin - Admin user session

### ISSUE THREAD

**Issue by levogirar** [wuwanahq/wuwana2#121]
We need create admin session in the webapp. This allows admins to modify company information, create new companies, etc.

**Comment by levogirar** [comment]
Needed for #76

**Comment by levogirar** [comment]
@Nils85 So this is done?

**Comment by Nils85** [comment]
I have to test on the server... Don't worry, when it's done I will close it ;)

**Comment by Nils85** [comment]
Admin users can now login and logout
