### ISSUE TITLE
v2.2 Homepage

### ISSUE THREAD

**Issue by levogirar** [wuwanahq/wuwana2#123]
Design and code the new homepage. Current homepage will become the search result page.

**Comment by Nils85** [comment]
@levogirar can you add some basic suggestions in the search?
Like "Coffee", "Beer", "Restaurant"...

<img width="617" alt="Screen Shot 2021-03-28 at 4 05 57 PM" src="https://user-images.githubusercontent.com/11949055/112755123-9f6afd00-8fdf-11eb-9575-9c9ec7aaa369.png">

_And don't forget to create a pull request before merging into develop-v22_ 😇

**Comment by levogirar** [comment]
I could try. Any suggestion on how to do that? 😝

**Comment by Nils85** [comment]
> I could try. Any suggestion on how to do that? 😝

Well, you created this interface, right?
So you just need to add HTML links that target this kind of URL: "/?search=beer"

**Comment by levogirar** [comment]
` listData = '<a href="/?search=' + userValue + '"><li>'+ userValue +'</li></a><hr>';` I added this to the javascript, but I meant how to generate more suggestions based on `userValue`
