### ISSUE TITLE
Error with the AJAX requests (only on the server)

### ISSUE THREAD

**Issue by Nils85** [wuwanahq/wuwana2#139]
**Ressource URL:**
https://wuwana.com/ajax/update-company.php

**Error on the browser:**
Failed to load resource: the server responded with a status of 500 (Internal Server Error) (update-company.php, line 0)

**Error on the server:**
PHP Fatal error:  Uncaught Error: Class 'DataAccess\SocialMediaData' not found in /var/www/wuwana2/ajax/update-company.php:11

**Comment by Nils85** [comment]
@levogirar Is this bug fixed?
Can you update company information now?

**Comment by levogirar** [comment]
@Nils85 I believe this is done.
