### ISSUE TITLE
Company 'All Text'

### ISSUE THREAD

**Issue by levogirar** [wuwanahq/wuwana2#151]
# Problem
Our topic extractor `NLPTagger` needs a lot of text in order to classify the company properly. Right now, we only use the Instagram description (which is rather short) to classify a company. 

# Solution
I want a new column in the company database where the all text from Instagram and their website is stored. 

## How would it work?
- When we scrape the company website, we create a long string of text (removing all tags like `<div>, <p>, <a>, <meta>, <script>`) and store it in the company database. It includes: the website description, website text, blog articles, product titles, contact information. 
- From Instagram, we store the all the text and add it to the same string.
- The NLPTagger will only target this column to classify the company.
- Each time we update (or scrape the company information), we replace the old text with the new text.
- If only the website is updated, but not Instagram, we only replace the website's text and we leave the Instagram text as it is.

## Future expansion 
- Find their CNAE number and add the description to the string.
- Find external articles (blogs, magazines, articles) and add it to the string.
- For customers/users reviews (yelp, tripadvisor, google, facebook), I think it would be better to have them separate. This could create two source of text: What the company say about itself vs what others say about the company.

**Comment by kakaye-mkubwa** [comment]
For the string that is to be stored in the database, what character shall I use to delimit the different pieces of information that will be scraped?

**Comment by levogirar** [comment]
I do not have any preference. However, perhaps this should fall in the `nlptagger` job. When we are going to classify the company, we join all the different fields of the company, then the python script does the job on the joined data. This way, we won't have to store duplicated data and make the `text replace` part irrelevant. 

What do you think?

**Comment by Nils85** [comment]
Hum...

> * If only the website is updated, but not Instagram, we only replace the website's text and we leave the Instagram text as it is.

This point is actually impossible with the current architecture because we update everything together during the scraping process.
To do that we first need a feature to be able to partially update company information... So, I think you can forget this point @kakaye-mkubwa 

> However, perhaps this should fall in the `nlptagger` job.

Maybe in the future but for now I don't think it does fetch more than only ONE column per company.
Currently the NLPTagger get only the column `Description` from the table `Company` if I remember correctly, right @levogirar ?

**Comment by levogirar** [comment]
@Nils85 Yes, you are correct. Perhaps, it is best to leave this on hold for the future. I haven't thought too much about the actual implementation.

**Comment by kakaye-mkubwa** [comment]
I have not gone through the nlptagger code in detail yet, so not much to contribute from my end. 

@levogirar the issue is on hold now?

**Comment by levogirar** [comment]
@kakaye-mkubwa I wanted the nlptagger to take use all the text from a company, so I thought it would make sense to integrate it now. @Nils85 points some very valid points and the job would involve more than what I originally thought. 

Let’s put this on hold for now.

**Comment by Nils85** [comment]
> For the string that is to be stored in the database, what character shall I use to delimit the different pieces of information that will be scraped?

You can use the constant `DataAccess::VALUES_DELIMITER`

**Comment by Nils85** [comment]
> Let’s put this on hold for now.

@levogirar Do you wanted to put this issue on hold or to close it??

**Comment by levogirar** [comment]
@Nils85 I will close this. In the future, I can come up with something better structured.
