### ISSUE TITLE
Login with navbar in admin pages

### ISSUE THREAD

**Issue by Nils85** [wuwanahq/wuwana2#164]
The navbar should ask to login when you try to access an admin page...

<img width="538" alt="Screen Shot 2021-03-27 at 3 01 17 PM" src="https://user-images.githubusercontent.com/11949055/112723174-8db92500-8f0d-11eb-95f3-6df69586a2ac.png">

So the the form currently in the header (when you add "?/login" in the URL) should be moved here instead.
Like that the red message will be removed in the main column (on the right).

**Comment by Nils85** [comment]
And at the same time we can fix the display bug when "Database" is clicked 🤪

**Comment by levogirar** [comment]
@Nils85 I have done some modification on my branch about this. I have merged it to `develop-v22` Now it looks like this 
![Screen Shot 2021-03-27 at 12 15 52](https://user-images.githubusercontent.com/54992530/112726941-4d9a7800-8ef6-11eb-9144-ae2b9b31b332.png)

I agree. `/?login` should lead to the admin page. Any idea on how to do this?
