### ISSUE TITLE
The search bar should block users who try to search nothing

### ISSUE THREAD

**Issue by Nils85** [wuwanahq/wuwana2#167]
I re-tested it today. It works when I search for something but it doesn't when I simply click on the search button without searching for anything. 

![Screen Shot 2021-03-28 at 10 33 16](https://user-images.githubusercontent.com/54992530/112755995-2b196500-8fb1-11eb-8ed1-1ce7c0deecd6.png)
![Screen Shot 2021-03-28 at 10 33 41](https://user-images.githubusercontent.com/54992530/112756001-2ce32880-8fb1-11eb-9c78-8c2664849a36.png)
![Screen Shot 2021-03-28 at 10 34 16](https://user-images.githubusercontent.com/54992530/112756002-2e145580-8fb1-11eb-9414-0179f8a14b83.png)

_Originally posted by @levogirar in https://github.com/wuwanahq/wuwana2/discussions/122#discussioncomment-540609_

**Comment by levogirar** [comment]
Perhaps related, the pagination doesn't work when the search query has multiple words or special character like accents `á` or `é`
