### ISSUE TITLE
Remove space on Category DB

### ISSUE THREAD

**Issue by wuwana** [wuwanahq/wuwana2#21]
![image](https://user-images.githubusercontent.com/68868137/96524059-39ff2d00-1245-11eb-9587-9dcbd03cbf34.png)

**Comment by levogirar** [comment]
@Nils85 I updated the Category database, but it seems that it does not fix the issue. Probably, it is something in the code itself.

**Comment by Nils85** [comment]
> @Nils85 I updated the Category database, but it seems that it does not fix the issue. Probably, it is something in the code itself.

Yes! It was a bug during the TSV file import
