### ISSUE TITLE
Only https

### ISSUE THREAD

**Issue by levogirar** [wuwanahq/wuwana2#26]
Force https:// on wuwana.com

**Comment by levogirar** [comment]
This might help:

https://www.webhostinghub.com/help/learn/website/ssl/force-website-to-use-ssl

**Comment by Nils85** [comment]
> This might help:
> 
> https://www.webhostinghub.com/help/learn/website/ssl/force-website-to-use-ssl

No it doesn't help because we want a redirection handled by the WebApp itself, not by the web server.

**Comment by kakaye-mkubwa** [comment]
SSL is not supported for php inbuilt servers, therefore, the web app will only run in the other configurations
