### ISSUE TITLE
Remove "wuwana" logo in the about box?

### ISSUE THREAD

**Issue by Nils85** [wuwanahq/wuwana2#32]
Currently:

![ScreenShot20201030at114459AM](https://user-images.githubusercontent.com/11949055/97727394-bb0cbe80-1aa6-11eb-9bde-9d9a8ba955e5.png)

Suggestion:

![ScreenShot20201030](https://user-images.githubusercontent.com/11949055/97727098-5f423580-1aa6-11eb-8df3-ea3f336e4ba3.png)

**Comment by levogirar** [comment]
I agree, it looks better.
