### ISSUE TITLE
Dynamic Open Graph Image

### ISSUE THREAD

**Issue by levogirar** [wuwanahq/wuwana2#59]
I want to dynamically generate an Open Graph Image from the company name. 

Currently, we are using the default mosaic image for every link of the website. I want to show a different one for each company page. Having the company name in the image. Ideally, this image is generated automatically for each company.

The image needs to be generated at the time of sharing. We do not want to store any picture.

For example: by sharing the link wuwana.com/companyA, an image is generated with the company name and logo.

Some images:
**Current**
![1*-7KmN_Omd2mc6X13tE8N_A](https://user-images.githubusercontent.com/54992530/102413272-ab97f500-3fc2-11eb-9714-721305983db5.png)

**Possible Design**
![Open Graph Dynamic](https://user-images.githubusercontent.com/54992530/102414114-f6663c80-3fc3-11eb-9038-e80158dcad90.jpg)

**Comment by Nils85** [comment]
Is that enhancement still to do?

**Comment by levogirar** [comment]
This has been completer.
