### ISSUE TITLE
Admin - Show error message when creating a company that already exist in the database

### ISSUE THREAD

**Issue by levogirar** [wuwanahq/wuwana2#78]

**Comment by Nils85** [comment]
It is a **bug**, not a new feature (enhancement)

**Comment by levogirar** [comment]
# The bounty for this issue is US$5

**Comment by levogirar** [comment]
# TO DO: How does it look? maybe a popup or modal.

**Comment by Nils85** [comment]
To solve this issue I need to answer this question:
What identify a company?

- its name?
- its Instagram profile page URL?
- another property??

**Comment by levogirar** [comment]
We will use the instagram profile page URL for now
